#!/usr/bin/env python3
"""Viewer outputs from a code-generated kernel, driven by the watershed's viewer_config.json.

Each variable in viewer_config.json names its model quantity ("source", with {unit} = sub-catchment id and
{segment} = its receiving segment; '*' globs allowed), an optional "divide_by" quantity (per-area fluxes), a
"scale", and whether the map shows it ("map": true). Every variable is charted.

  spec    write the kernel output list for `ohq_generate --outputs` (every source and divide_by quantity)
  sample  run the kernel hourly on its baked forcing and write the viewer files (docs/viewer_data.md) for a
          chosen "now": a stand-in for the engine, which will write the same files every cycle

  twin_outputs.py spec   --config watersheds/RockCreek/viewer_config.json --out build/kernels/RockCreek_outputs.txt
  twin_outputs.py sample --config watersheds/RockCreek/viewer_config.json --kernel <lib.so> \
      --params "p_Ksat=3.19747,..." --rain-dir <forcing dir> --obs-dir <obs dir> --now 2019-07-01 --out viewer/sample
"""
import argparse
import ctypes
import datetime as dt
import fnmatch
import json
import re
import shutil
import time
from pathlib import Path

import numpy as np
import pandas as pd

ROOT = Path(__file__).resolve().parents[1]
EPOCH = dt.datetime(1899, 12, 30)
GAGES = {"01647850": "Turkey Branch near Rockville", "01648000": "Rock Creek at Sherrill Dr",
         "01648010": "Rock Creek at Joyce Rd"}


def serial(d):
    return (d - EPOCH).total_seconds() / 86400.0


def units_table(cfg_path, cfg):
    """unit id -> placeholder values, from the units layer"""
    gis = json.loads((cfg_path.parent / cfg["layers"]["units"]["url"]).read_text())
    idf = cfg["layers"]["units"]["id_field"]
    return {f["properties"][idf]: {"unit": f["properties"][idf], "segment": f["properties"]["receiving_segment"]}
            for f in gis["features"]}


def fill(pattern, ph):
    return re.sub(r"\{(\w+)\}", lambda m: ph[m.group(1)], pattern)


def variables(cfg):
    for e in cfg["elements"]:
        for v in e["variables"]:
            yield e, v


def cmd_spec(a):
    cfg_path = Path(a.config)
    cfg = json.loads(cfg_path.read_text())
    lines = set()
    for ph in units_table(cfg_path, cfg).values():
        for _, v in variables(cfg):
            for key in ("source", "divide_by"):
                if key in v:
                    obj, q = fill(v[key], ph).split(":", 1)
                    lines.add(f"{obj} {q}")
    Path(a.out).write_text("# generated by tools/twin_outputs.py spec from " + str(cfg_path) + "\n"
                           + "\n".join(sorted(lines)) + "\n")
    print(f"wrote {a.out}: {len(lines)} object/quantity lines")


class Kernel:
    def __init__(self, path):
        k = ctypes.CDLL(str(path))
        k.ohq_kernel_create.restype = ctypes.c_void_p
        for n in ("ohq_kernel_output_name", "ohq_kernel_parameter_name", "ohq_kernel_observation_name"):
            getattr(k, n).restype = ctypes.c_char_p
        k.ohq_kernel_simulation_start.restype = ctypes.c_double
        k.ohq_kernel_run_to.argtypes = [ctypes.c_void_p, ctypes.c_double]
        k.ohq_kernel_set_parameter.argtypes = [ctypes.c_void_p, ctypes.c_int, ctypes.c_double]
        k.ohq_kernel_observation_at.argtypes = [ctypes.c_void_p, ctypes.c_int, ctypes.c_int,
                                                ctypes.POINTER(ctypes.c_double), ctypes.POINTER(ctypes.c_double)]
        for n in ("ohq_kernel_initialize", "ohq_kernel_apply_parameters", "ohq_kernel_solution_failed"):
            getattr(k, n).argtypes = [ctypes.c_void_p]
        k.ohq_kernel_observation_count.argtypes = [ctypes.c_void_p, ctypes.c_int]
        k.ohq_kernel_outputs.argtypes = [ctypes.c_void_p, ctypes.POINTER(ctypes.c_double)]
        self.k = k
        self.h = ctypes.c_void_p(k.ohq_kernel_create())
        self.names = [k.ohq_kernel_output_name(i).decode() for i in range(k.ohq_kernel_n_outputs())]
        self.buf = (ctypes.c_double * max(1, len(self.names)))()

    def outputs(self):
        self.k.ohq_kernel_outputs(self.h, self.buf)
        return np.frombuffer(self.buf, dtype=np.float64, count=len(self.names)).copy()


def cmd_sample(a):
    cfg_path = Path(a.config)
    cfg = json.loads(cfg_path.read_text())
    out = Path(a.out)
    for d in ("outputs/units", "outputs/gages", "gis"):
        (out / d).mkdir(parents=True, exist_ok=True)
    for f in (cfg_path.parent / "gis").glob("*.geojson"):
        shutil.copy(f, out / "gis" / f.name)
    units = units_table(cfg_path, cfg)

    K = Kernel(a.kernel)
    k = K.k
    index = {n: i for i, n in enumerate(K.names)}

    def resolve(pattern, ph):
        name = fill(pattern, ph)
        if name in index:
            return index[name]
        hits = sorted(n for n in K.names if fnmatch.fnmatchcase(n, name))
        return index[hits[0]] if hits else None

    # (unit, element, variable) -> (output index, divide_by index or None)
    plan, missing = {}, []
    for u, ph in units.items():
        for e, v in variables(cfg):
            i = resolve(v["source"], ph)
            j = resolve(v["divide_by"], ph) if "divide_by" in v else None
            if i is None or ("divide_by" in v and j is None):
                missing.append(f"{u} {e['id']}:{v['id']}")
                continue
            plan[(u, e["id"], v["id"])] = (i, j)
    if missing:
        print(f"{len(missing)} variable(s) not in the kernel outputs, e.g. {missing[:4]}")

    k.ohq_kernel_initialize(K.h)
    pnames = [k.ohq_kernel_parameter_name(i).decode() for i in range(k.ohq_kernel_n_parameters())]
    for kvp in filter(None, a.params.split(",")):
        n, v = kvp.split("=")
        k.ohq_kernel_set_parameter(K.h, pnames.index(n.strip()), float(v))
    k.ohq_kernel_apply_parameters(K.h)

    ot = cfg.get("output_times", {})
    now = serial(dt.datetime.fromisoformat(a.now))
    t_from, t_end = now - ot.get("history_days", 45), now + a.forecast_days
    step = ot.get("chart_step_hours", 1) / 24.0
    times = np.arange(t_from, t_end + 1e-9, step)
    onames = [k.ohq_kernel_observation_name(i).decode() for i in range(k.ohq_kernel_n_observations())]
    tt, vv = ctypes.c_double(), ctypes.c_double()

    def obs_series(i):
        n = k.ohq_kernel_observation_count(K.h, i)
        a_ = np.empty((n, 2))
        for j in range(n):
            k.ohq_kernel_observation_at(K.h, i, j, ctypes.byref(tt), ctypes.byref(vv))
            a_[j] = tt.value, vv.value
        return a_

    # the run is cached (--cache): re-writing the files after a config change does not re-run the model
    cache = Path(a.cache) if a.cache else None
    Y = None
    if cache and cache.exists() and cache.stat().st_mtime > Path(a.kernel).stat().st_mtime:
        z = np.load(cache, allow_pickle=True)
        if list(z["times"]) == list(times) and str(z["params"]) == a.params:
            Y, obs = z["Y"], z["obs"].item()
            print(f"model run from {cache}")
    if Y is None:
        t0 = k.ohq_kernel_simulation_start()
        clock = time.time()
        k.ohq_kernel_run_to(K.h, ctypes.c_double(float(times[0])))
        rows = []
        for t in times:
            k.ohq_kernel_run_to(K.h, ctypes.c_double(float(t)))
            rows.append(K.outputs())
        if k.ohq_kernel_solution_failed(K.h):
            raise SystemExit("kernel solve failed")
        Y = np.vstack(rows)
        obs = {n: obs_series(i) for i, n in enumerate(onames)}
        print(f"ran {times[-1] - t0:.0f} days in {time.time() - clock:.0f} s; {len(K.names)} outputs, {len(times)} times")
        if cache:
            np.savez_compressed(cache, Y=Y, times=times, params=a.params, obs=np.array(obs, dtype=object))

    def values(u, e, v):
        ij = plan.get((u, e["id"], v["id"]))
        if ij is None:
            return None
        y = Y[:, ij[0]]
        if ij[1] is not None:
            y = y / Y[:, ij[1]]
        return y * v.get("scale", 1.0)

    def r(x):
        return [None if not np.isfinite(z) else float(f"{z:.4g}") for z in x]

    mstep = max(1, int(round(ot.get("map_step_hours", 3) / ot.get("chart_step_hours", 1))))
    mi = np.arange(0, len(times), mstep)
    mstate = {"now": now, "times": [round(float(x), 5) for x in times[mi]], "variables": {}}
    for e, v in variables(cfg):
        if not v.get("map"):
            continue
        key = f"{e['id']}:{v['id']}"
        mstate["variables"][key] = {}
        for u in units:
            y = values(u, e, v)
            # stream variables are keyed by reach id; the reaches layer uses the unit id
            mstate["variables"][key][u] = None if y is None else r(y[mi])
    (out / "outputs/map_state.json").write_text(json.dumps(mstate, separators=(",", ":")))

    tl = [round(float(x), 5) for x in times]
    for u in units:
        series = {}
        rf = Path(a.rain_dir) / f"precip_sc{int(u[2:]):02d}.csv"
        if rf.exists():
            p = np.loadtxt(rf, delimiter=",", ndmin=2)
            p = p[(p[:, 1] > t_from) & (p[:, 0] < t_end)]
            hr = np.floor((p[:, 0] - t_from) / step + 1e-6).astype(int)
            depth = np.bincount(hr[(hr >= 0) & (hr < len(times))], weights=p[(hr >= 0) & (hr < len(times)), 2] * 1000,
                                minlength=len(times))
            series["rain"] = {"label": "Rainfall", "unit": "mm/h" if step < 0.05 else "mm/step",
                              "v": r(depth / (step * 24))}
        for e, v in variables(cfg):
            y = values(u, e, v)
            if y is not None:
                series[f"{e['id']}:{v['id']}"] = {"label": f"{e['label']}: {v['label']}", "unit": v["unit"],
                                                   "v": r(y)}
        # one time axis for the file; a series without its own "t" uses it
        (out / f"outputs/units/{u}.json").write_text(
            json.dumps({"id": u, "now": now, "t": tl, "series": series}, separators=(",", ":")))

    # gages: model from the kernel's own observations (Q in m3/d, H in m), USGS from the calibration files
    for gid, name in GAGES.items():
        series = {}
        for key, scale, unit, lab, kind in (("Q", 1 / 86400, "m3/s", "Flow", "flow"), ("H", 1, "m", "Stage", "stage")):
            if f"{key}_{gid}" not in obs:
                continue
            m = obs[f"{key}_{gid}"]
            idx = np.clip(np.searchsorted(m[:, 0], times), 0, len(m) - 1)
            series[f"{key}_model"] = {"label": f"{lab}, model", "unit": unit, "t": tl, "v": r(m[idx, 1] * scale)}
            f = Path(a.obs_dir) / f"{gid}_{kind}_cal.csv"
            if f.exists():
                o = np.loadtxt(f, delimiter=",", ndmin=2)
                o = o[(o[:, 0] >= t_from) & (o[:, 0] <= now)]
                do = pd.Series(o[:, 1] * scale, index=np.floor((o[:, 0] - t_from) / step) * step + t_from).groupby(level=0).mean()
                series[f"{key}_obs"] = {"label": f"{lab}, USGS", "unit": unit,
                                        "t": [round(float(x), 5) for x in do.index], "v": r(do.values)}
        (out / f"outputs/gages/{gid}.json").write_text(json.dumps(
            {"id": gid, "name": name, "now": now, "flood_stage_m": None, "series": series}, separators=(",", ":")))

    (out / "outputs/status.json").write_text(json.dumps(
        {"issued_utc": a.now + "T00:00:00Z", "now": now, "forecast_end": t_end,
         "rain_source": "sample (calibration forcing replayed)", "stale": False}))
    vc = dict(cfg)
    vc["title"] = cfg["title"] + " (sample data)"
    (out / "viewer_config.json").write_text(json.dumps(vc, indent=1))
    size = sum(f.stat().st_size for f in out.rglob("*") if f.is_file())
    print(f"wrote {out}: {len(units)} units, {size / 1e6:.1f} MB")


def main():
    ap = argparse.ArgumentParser()
    sub = ap.add_subparsers(dest="cmd", required=True)
    s = sub.add_parser("spec")
    s.add_argument("--config", required=True)
    s.add_argument("--out", required=True)
    s = sub.add_parser("sample")
    s.add_argument("--config", required=True)
    s.add_argument("--kernel", required=True)
    s.add_argument("--params", default="")
    s.add_argument("--rain-dir", required=True)
    s.add_argument("--obs-dir", required=True)
    s.add_argument("--now", default="2019-07-01")
    s.add_argument("--forecast-days", type=int, default=7)
    s.add_argument("--out", default=str(ROOT / "viewer/sample"))
    s.add_argument("--cache", help="npz file caching the model run")
    a = ap.parse_args()
    cmd_spec(a) if a.cmd == "spec" else cmd_sample(a)


if __name__ == "__main__":
    main()
